---
name: Build Fedora Kernel

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: "Get version"
        id: get_version
        run: echo ::set-output name=VERSION::$(echo ${{ github.event.head_commit.message }} | sed 's/ \[rel\]//')

      - name: "Increase Disk Space"
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc

      - name: "Checkout"
        uses: actions/checkout@v3
      
      - name: "Build"
        run: |
          mkdir -p ~/rpmbuild
          echo "$RPM_SIGNING_KEY" > ./rpm_signing_key
          docker run -t -v "$PWD":/repo fedora:36 /bin/bash -c "/repo/build.sh"
        env: 
          RPM_SIGNING_KEY: ${{ secrets.RPM_SIGNING_KEY }}

      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: t2linux-fedora-kernel-${{ steps.get_version.outputs.VERSION }}
          path: ${{ github.workspace }}/output/RPMS/*/*

      - name: Release
        if: ${{ github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, '[rel]') }}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.workspace }}/output/RPMS/*/*.rpm
          tag_name: ${{ steps.get_version.outputs.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Update repo
        run: |
          curl \
            -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.PAT }}" "https://api.github.com/repos/sharpenedblade/t2linux-fedora-repo/actions/workflows/31063766/dispatches" -d '{"ref":"main"}'
