name: Build
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Increase Disk Space"
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo rm -rf /home/linuxbrew
          sudo apt-get remove -y --purge fonts-noto-color-emoji subversion \
              sshpass g++ gcc gnupg2 imagemagick jq libmagic-dev \
              libmagickcore-dev	libmagickwand-dev	libssl-dev \
              mercurial openssh-client p7zip-full	ftp bison
          sudo apt-get autoremove -y

      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Build"
        run: |
          mkdir -p _output
          docker run \
            -t \
            --privileged \
            -v "$PWD":/repo \
            ghcr.io/t2linux/fedora-dev:latest \
            /repo/build-packages.sh

      - name: "Sign Packages"
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          docker run \
            -t \
            -v $PWD:/repo \
            -e RPM_SIGNING_PRIVATE_KEY_B64 \
            ghcr.io/t2linux/fedora-dev:latest \
            /repo/sign-packages.sh
        env:
          RPM_SIGNING_PRIVATE_KEY_B64: ${{ secrets.RPM_SIGNING_PRIVATE_KEY_B64 }}

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: _output/*.rpm

      - name: "Release"
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            _output/*.rpm

      - name: "Build DNF Repo"
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          docker run -t \
            -v $PWD:/repo \
            ghcr.io/t2linux/fedora-kernel-build:latest \
            /repo/generate-dnf-repo.sh

      - name: "Deploy To Repo"
        if: startsWith(github.ref, 'refs/tags/v')
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=dnf-repo --prod
