name: Checks
on:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Lint"
        run: |
          docker run \
            -v "$PWD":/repo \
            ghcr.io/t2linux/fedora-dev:latest \
            /repo/lint.sh
