name: CI
on:
  push:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  deploy:
    needs: ["build"]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: ["build"]
    uses: ./.github/workflows/release.yml
    secrets: inherit
