name: Deploy DNF repo

concurrency:
  group: deploy
  cancel-in-progress: true

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Download release"
        uses: robinraju/release-downloader@v1.8
        with:
          latest: true
          fileName: "*"
          out-file-path: "builddir/packages"

      - name: "Build DNF Repo"
        run: |
          docker run -t \
            -v $PWD:/repo \
            -e SIGNING_KEY \
            ghcr.io/t2linux/fedora-dev:latest \
            /repo/create-repo.sh
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY_F38 }}

      - name: "Deploy DNF repo"
        uses: nwtgck/actions-netlify@v2.0
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          publish-dir: builddir/dnf-repo
          production-deploy: ${{ startsWith(github.ref, 'refs/tags/v') }}
