name: Deploy
on:
  workflow_call:

jobs:
   deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Download Artifacts"
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: /tmp/output

      - name: "Build DNF Repo"
        run: |
          mkdir /tmp/repo
          docker run -t -v /tmp/output:/output -v /tmp/rpm-repo:/rpm-repo fedora:38 /bin/bash -c "/repo/build-repo.sh"
          cp -r /tmp/rpm-repo ./deploy

      - name: "Deploy To Repo"
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=deploy --prod