name: Release
on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: "Download Artifacts"
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: /tmp/output
    
      - name: "Check For Packages"
        run: |
          stat --printf='' /tmp/output/kernel*.rpm
          stat --printf='' /tmp/output/t2linux-config*.rpm
          stat --printf='' /tmp/output/t2linux-repo*.rpm
          stat --printf='' /tmp/output/t2linux-audio*.rpm

      - name: "Release"
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            /tmp/output/*.rpm
