---
name: Update T2Linux Fedora Repos
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - uses: robinraju/release-downloader@v1.7
        with: 
          latest: true
          fileName: "*.rpm"
          out-file-path: "/tmp/output/"

      - name: Update repo
        run: |
          mkdir /tmp/repo
          docker run -t -v /tmp/output:/output -v /tmp/rpm-repo:/rpm-repo fedora:38 /bin/bash -c "/repo/build-repo.sh"
          cp -r /tmp/rpm-repo ./deploy

      - name: Upload
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=deploy --prod
